### ISSUE TITLE
How to transfer object to RGBD images?

### ISSUE THREAD

**Issue by zxy110** [ytrock/THuman2.0-Dataset#1]
Hi,

I found RGBD images are regarded as inputs in the paper, but the datasets provided are obj, mtl and jpeg files.
Could you please tell me how you transfer the obj format to RGBD format? Thanks so much.

Sincerely,
zxy110

**Comment by ytrock** [comment]
Hi Xiaoyu, we rendered the RGBD images using a PRT-based renderer we implemented using c++, if you think the RGBD images are useful, perhaps we can also release our rendered RGBD images, please standing by for the updates :)

**Comment by zxy110** [comment]
Hi Tao, I solved it by the open3d visualization class [here](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html).
Thank you very much!

**Comment by mmmcn** [comment]
@zxy110 Hi Xiaoyu, could you describe how you got the RGBD images, by the way, what about camera intrinsic parameters?

**Comment by zxy110** [comment]
@mmmcn Hi, I use the [open3d.visualization.Visualizer](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html) implement. I get the RGBD images by [capture_screen_image](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html) function, and change view by [open3d.visualization.ViewControl](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html). You can read and write the camera intrinsic parameters by [open3d.io](http://www.open3d.org/docs/release/python_api/open3d.io.read_pinhole_camera_intrinsic.html) function.
