### ISSUE TITLE
Release rendered RGBD images

### ISSUE THREAD

**Issue by miliRs** [ytrock/THuman2.0-Dataset#11]
Hello M.r. Thank you for nice work! do you have plan to release your rendered RGBD images?

**Comment by ytrock** [comment]
Thanks for your attention.
Sorry, we dont have a plan to release the rendered RGBD images, cause different tasks may require different rendering configurations. 
Maybe you can find related rendering code base at [here](https://github.com/shunsukesaito/PIFu/blob/f0a9c99ef887e1eb360e865a87aa5f166231980e/apps/render_data.py).

**Comment by YuliangXiu** [comment]
> Hello M.r. Thank you for nice work! do you have plan to release your rendered RGBD images?

You can check this pull request (https://github.com/ytrock/THuman2.0-Dataset/pull/13) for the rendering purpose.
