### ISSUE TITLE
Why I got the wrong global orient results

### ISSUE THREAD

**Issue by jhkim0759** [ytrock/THuman2.0-Dataset#12]
![그림1](https://user-images.githubusercontent.com/77155480/189826378-4eff7980-dcd1-4818-a264-287bffd75f34.png)

I rendered the obj with pytorch3d library and fit the SMPL skinned model using the parameters provided.
but, I got the results as above. 
I think this is upside down result. Can you help me to get the correct results?

**Comment by ytrock** [comment]
Dear jhkim0759,

can you first try to generate the corresponding SMPL mesh and save it as .obj file, and then check the alignment between the two obj meshes using the Meshlab?

**Comment by ytrock** [comment]
That's weird, when generating smpl-x meshes, did you use the provided poses which already include the global RT?
Or you can paste your code for generating the smpl-x meshes at here.

**Comment by jhkim0759** [comment]
```
smplr = SMPLR()

params_dir = "../dataset/THuman/THuman2.0_smplx/0525/smplx_param.pkl"

db = np.load(params_dir, allow_pickle=True)
dict_ = {}
for key in db:
    dict_[key] = torch.tensor(db[key])
    
params_dir = "../obj2png/ICON/data/thuman2/smpl/0525.pkl"
with open(params_dir, 'rb') as f:
    dict_ = pickle.load(f)
    
global_ori = torch.from_numpy(dict_["global_orient"])[0]
pose = torch.cat([global_ori, torch.from_numpy(dict_["body_pose"][0])],0)
verts = smplr(pose.reshape(1,-1,3,3).float(),torch.from_numpy(beta).reshape(1,-1).float(), pose2rot=False)["verts"]

verts = verts + dict_['transl']

renderer = Renderer(resolution=(1024, 1024), orig_img=True, wireframe=False )
img = renderer.render(camera_view, verts[0], [1,1,0,0])
```

This the code what is used.
The SMPLR Model is from ROMP, and Renderer is from PARE. 

Thank you

**Comment by jhkim0759** [comment]
I think the SMPL regressor is based on vibe form. 
That's why the verts show the opposite.
Thank you for discuss with me

**Comment by ytrock** [comment]
you are welcome :)

**Comment by ytrock** [comment]
You are welcome :) Thanks for your attention.
