### ISSUE TITLE
Rendering Pipeline for THuman2.0

### ISSUE THREAD

**Issue by YuliangXiu** [ytrock/THuman2.0-Dataset#14]
Hi @ytrock 

THuman2.0 has been widely used in many downstream tasks, including image-based clothed human reconstruction. I have built up a rendering pipeline and made a pull request for it (https://github.com/ytrock/THuman2.0-Dataset/pull/13), thus other users could render multi-view RGB / Depth / Normal from THuman2.0 and compute the camera-view visibility as well effortlessly.

![image](https://user-images.githubusercontent.com/7944350/236676464-9c0ee666-628d-4cf7-a0ce-5f9f30b29429.png)

Best
Yuliang

**Comment by ytrock** [comment]
Cool, thanks for your efforts!
