### ISSUE TITLE
How to download THuman2.1?

### ISSUE THREAD

**Issue by River-Zhang** [ytrock/THuman2.0-Dataset#17]
Fantastic work! I saw the news that THuman2.1 contains 2,500 scans. I was wondering where I can download the data and the SMPL-X models. Thanks very much!

**Comment by ytrock** [comment]
Hi, thanks for your attention! It will be released soon! (with in this week!)

**Comment by River-Zhang** [comment]
Thanks！Waiting for your release!

**Comment by wyiguanw** [comment]
Hi, I saw the SMPL-X for THuman2.1 is released, How can I download the models' data?

**Comment by ZhenhuiL1n** [comment]
Hi, is Thuman2.1 out now? How can I download it?

**Comment by LuckyOne09** [comment]
Hello @ytrock , is there a download method available for THuman2.1 now? I'm very excited to see the new dataset advance the field.

**Comment by ytrock** [comment]
Yes, we've upgraded the dataset, you can send us a new request to get the latest one.
