### ISSUE TITLE
How to download a dataset: I sent a completed form "THUman2.0_Agreement.pdf" to email addresses a week ago, but I did not receive a reply with a link.

### ISSUE THREAD

**Issue by lsi1** [ytrock/THuman2.0-Dataset#19]
I sent a completed form "THUman2.0_Agreement.pdf" to email addresses a week ago, but I did not receive a reply with a link.

**Comment by ytrock** [comment]
sorry for the inconvenience. Please tell us your email address and we will share the dataset ASAP.

**Comment by Mr-ind1fferent** [comment]
> sorry for the inconvenience. Please tell us your email address and we will share the dataset ASAP.

I also sent an email, and nearly a week later, I haven't received a reply. My email address is swwu2001@163.com.

**Comment by TiantianWang** [comment]
> sorry for the inconvenience. Please tell us your email address and we will share the dataset ASAP.

Just wondering if we can access THUman2.1 dataset now.

**Comment by ytrock** [comment]
Yes, please send me an email attached with the application form.

**Comment by TiantianWang** [comment]
> Yes, please send me an email attached with the application form.

Just sent the application form via my school's email. Could you check it when you have some time?

**Comment by TShoreWind** [comment]
我用QQ邮箱发送了邮件，还没有得到回复。

**Comment by ytrock** [comment]
Please check your spam folder for the dataset sharing link if you have already sent an email but have not received it yet. If it is not there, please send us another email and we will process it as soon as possible.
