### ISSUE TITLE
Misalignment between scan and its SMPL-X fit on THuman2.1

### ISSUE THREAD

**Issue by PawtingDev** [ytrock/THuman2.0-Dataset#23]
Great work on extending the dataset to over 2k scans! But I encountered a problem while processing the updated THuman2.1.
I imported a same set of data(0001) to blender. Above/selected smplx fit is from THuman2.1, and the below one is from THuman2.0. Scans from both dataset seem to be aligned, such misalignment between scan and its smpl-x fit do not exist in THuman2.0.
![image](https://github.com/ytrock/THuman2.0-Dataset/assets/100947659/e980a17b-16ee-4a66-a177-c54472ddc6fc)
And see also in meshlab.
![image](https://github.com/ytrock/THuman2.0-Dataset/assets/100947659/03c66c51-3257-4903-9b2e-ece69723d9f8)

**Comment by ytrock** [comment]
Got it. I will check this problem.

**Comment by zhanghebuaa** [comment]
We have noticed the issue of inconsistent parameter representations between the two batches of data before and after 526, and are working on it. Currently, the following code will solve your problem:
    params_ori = np.load('THuman2.1/smplx/0000/smplx_param.pkl' ,allow_pickle=True) 
    m_smplx = smplx.SMPLX('E:/bodyModels/smplx', gender='male', use_pca=True, num_pca_comps=12)
    smpl_out = m_smplx.forward(
        transl=torch.tensor(params_ori['translation']).reshape([-1, 3]) / params_ori['scale'],
        global_orient=torch.tensor(params_ori['global_orient']),
        body_pose=torch.tensor(params_ori['body_pose']),
        betas=torch.tensor(params_ori['betas']),
        left_hand_pose=torch.tensor(params_ori['left_hand_pose']),
        right_hand_pose=torch.tensor(params_ori['right_hand_pose']),
        expression=torch.tensor(params_ori['expression']),
        jaw_pose=torch.tensor(params_ori['jaw_pose']),
        leye_pose=torch.tensor(params_ori['leye_pose']),
        reye_pose=torch.tensor(params_ori['reye_pose'])
    )
    vertices = smpl_out.vertices.detach().cpu().numpy()[0] * params_ori['scale']
    m_model = trimesh.Trimesh(vertices=vertices, faces=m_smplx.faces, process=False)
    m_model.export('debug/smplx_0000.obj' )

**Comment by jinnan-chen** [comment]
It seems the tranlstion is wrong, is there any update on this?

**Comment by ytrock** [comment]
We've just updated the SMPL-X fittings and also provided the code for converting SMPL-X paras to meshes. Please checkout the readme for the newest download link.

**Comment by wenj** [comment]
Thanks for updating the parameters! It seems like "scale" is missing in the new released data. When I ran the the provided converting code, I got:
```
Traceback (most recent call last):
  File "Thuman_released.py", line 30, in <module>
    vertices = smpl_out.vertices.detach().cpu().numpy()[0] * params['scale']
KeyError: 'scale'
```
Is there somewhere to find the scale?

Thanks!

**Comment by ytrock** [comment]
Just fixed, please download using the updated link on the webpage.

**Comment by kkaytekin** [comment]
Maybe related issue: The 3D scans axes are different in new samples:
![image](https://github.com/user-attachments/assets/ebb60ab8-e2ba-4519-bfac-b33a7aecf51d)

And their scale is also inconsistent:
![image](https://github.com/user-attachments/assets/b806eb5c-0d10-4d99-8d51-27f6699345ce)

Is this also updated on the last version? Then maybe I have an older download link :/

**Comment by zhanghebuaa** [comment]
> Maybe related issue: The 3D scans axes are different in new samples: ![image](https://private-user-images.githubusercontent.com/23405318/362208009-ebb60ab8-e2ba-4519-bfac-b33a7aecf51d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTQxMTksIm5iZiI6MTcyNTg1MzgxOSwicGF0aCI6Ii8yMzQwNTMxOC8zNjIyMDgwMDktZWJiNjBhYjgtZTJiYS00NTE5LWJmYWMtYjMzYTdhZWNmNTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOWE0MzIzZTQwZjUwM2UwNDBkNDQ1NzA3YjY3MTAyYzhiYzViMjYyM2ZhNmY4MGY5NDU0MDRhYmRiY2NmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U4nrzznS2G9BWOE0Lq0EJy7WD4pWHlG_JeQ92vOYeoo)
> 
> And their scale is also inconsistent: ![image](https://private-user-images.githubusercontent.com/23405318/362208452-b806eb5c-0d10-4d99-8d51-27f6699345ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTQxMTksIm5iZiI6MTcyNTg1MzgxOSwicGF0aCI6Ii8yMzQwNTMxOC8zNjIyMDg0NTItYjgwNmViNWMtMGQxMC00ZDk5LThkNTEtMjdmNjY5OTM0NWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZmYxNzA3MTkwMWQxNTM1ZTgwZGZjN2I4ZDExY2JiODkzOTRhZDBhNGVjYTJlN2RkMzQ0OTYyZGVkZmY2NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BjgfuoRUg8kMXSWiP-QqRQSqhuRJqiXpKY8yPDnQBjg)
> 
> Is this also updated on the last version? Then maybe I have an older download link :/

The scale of the meshs in different frames may be different, but the scale of the mesh and smplx in the same frame is the same.
