### ISSUE TITLE
bad rendering results on Thuman2.1 by icon

### ISSUE THREAD

**Issue by WRY0627** [ytrock/THuman2.0-Dataset#24]
hi, thank you for this great work! When I used icon to render RGB/depth/Normal map, it worked great! but on 2.1(samples after 525), only legs or shoes were shown. Is this caused by differences in certain camera parameters between the two samples？
![image](https://github.com/ytrock/THuman2.0-Dataset/assets/114843395/19eed865-1cc4-445d-8f06-f4ef26557b82)

**Comment by zhanghebuaa** [comment]
The data before and after 525 belong to two different batches, and their coordinate systems and scales are slightly different.

**Comment by zhanghebuaa** [comment]
The reconstruction system does not have an exact coordinated system and scale. I suggest normalizing based on the dimensions (length, width, height) and center of the model.

**Comment by zhanghebuaa** [comment]
When using our system, we manually normalize the data based on the dimensions (length, width, and height) of the model according to our specific requirements. Our reconstruction system does not output a fixed scale and coordinate system.



At 2024-04-28 20:42:10, "WRY0627" ***@***.***> wrote:

May I ask where can I get their coordinated systems and scales?

**Comment by WRY0627** [comment]
Thank you very much for your answer.

**Comment by LuckyOne09** [comment]
Hello @WRY0627, Could you please provide guidance on how to download Thuman 2.1? I currently only see the download method for Thuman 2.0 in the README.md file. Thank you!

**Comment by WRY0627** [comment]
I directly filled in the data set application and provided the data of 2.1

---- Replied Message ----
| From | Yunsheng ***@***.***> |
| Date | 09/14/2024 15:22 |
| To | ***@***.***> |
| Cc | WRY0627 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ytrock/THuman2.0-Dataset] bad rendering results on Thuman2.1 by icon (Issue #24) |

Hello @WRY0627, Could you please provide guidance on how to download Thuman 2.1? I currently only see the download method for Thuman 2.0 in the README.md file. Thank you!

**Comment by ytrock** [comment]
Hi all, I've updated the request form for THuman2.1 and now you can fill out the form and send it to me by email.

**Comment by t973288913** [comment]
> hi, thank you for this great work! When I used icon to render RGB/depth/Normal map, it worked great! but on 2.1(samples after 525), only legs or shoes were shown. Is this caused by differences in certain camera parameters between the two samples？ ![image](https://private-user-images.githubusercontent.com/114843395/325489694-19eed865-1cc4-445d-8f06-f4ef26557b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTM2NzUsIm5iZiI6MTczNDMxMzM3NSwicGF0aCI6Ii8xMTQ4NDMzOTUvMzI1NDg5Njk0LTE5ZWVkODY1LTFjYzQtNDQ1ZC04ZjA2LWY0ZWYyNjU1N2I4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzkzNmU3ODFmMjc4OGM2MGQ0YjE3MzY2Njk2YTBlMjQ5M2ZlMzAxMmE5MWFhZmE3ZDBiOTNmYjBlOTk1YTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JdyZiAgNC3_SCW2Y8cLC6bKcfv763wVKdnAGWOB5fDQ)

Hi,I have the same problem now. How did you solve it？

**Comment by CHMimilanlan** [comment]
> > hi, thank you for this great work! When I used icon to render RGB/depth/Normal map, it worked great! but on 2.1(samples after 525), only legs or shoes were shown. Is this caused by differences in certain camera parameters between the two samples？ ![image](https://private-user-images.githubusercontent.com/114843395/325489694-19eed865-1cc4-445d-8f06-f4ef26557b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTM2NzUsIm5iZiI6MTczNDMxMzM3NSwicGF0aCI6Ii8xMTQ4NDMzOTUvMzI1NDg5Njk0LTE5ZWVkODY1LTFjYzQtNDQ1ZC04ZjA2LWY0ZWYyNjU1N2I4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzkzNmU3ODFmMjc4OGM2MGQ0YjE3MzY2Njk2YTBlMjQ5M2ZlMzAxMmE5MWFhZmE3ZDBiOTNmYjBlOTk1YTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JdyZiAgNC3_SCW2Y8cLC6bKcfv763wVKdnAGWOB5fDQ)
> 
> Hi,I have the same problem now. How did you solve it？

Hi, I have met similar problem, have you solve this?

**Comment by zhanghebuaa** [comment]
The model and smplx are aligned in our data. The model has no absolute scale, and the model coordinate system and size are different before and after 525. I think normalization should solve your problem.

**Comment by zhanghebuaa** [comment]
> > > hi, thank you for this great work! When I used icon to render RGB/depth/Normal map, it worked great! but on 2.1(samples after 525), only legs or shoes were shown. Is this caused by differences in certain camera parameters between the two samples？ ![image](https://private-user-images.githubusercontent.com/114843395/325489694-19eed865-1cc4-445d-8f06-f4ef26557b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTM2NzUsIm5iZiI6MTczNDMxMzM3NSwicGF0aCI6Ii8xMTQ4NDMzOTUvMzI1NDg5Njk0LTE5ZWVkODY1LTFjYzQtNDQ1ZC04ZjA2LWY0ZWYyNjU1N2I4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzkzNmU3ODFmMjc4OGM2MGQ0YjE3MzY2Njk2YTBlMjQ5M2ZlMzAxMmE5MWFhZmE3ZDBiOTNmYjBlOTk1YTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JdyZiAgNC3_SCW2Y8cLC6bKcfv763wVKdnAGWOB5fDQ)
> > 
> > 
> > Hi,I have the same problem now. How did you solve it？
> 
> Hi, I have met similar problem, have you solve this?

The model and smplx are aligned in our data. The model has no absolute scale, and the model coordinate system and size are different before and after 525. I think normalization should solve your problem.

**Comment by zhanghebuaa** [comment]
> > hi, thank you for this great work! When I used icon to render RGB/depth/Normal map, it worked great! but on 2.1(samples after 525), only legs or shoes were shown. Is this caused by differences in certain camera parameters between the two samples？ ![image](https://private-user-images.githubusercontent.com/114843395/325489694-19eed865-1cc4-445d-8f06-f4ef26557b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTM2NzUsIm5iZiI6MTczNDMxMzM3NSwicGF0aCI6Ii8xMTQ4NDMzOTUvMzI1NDg5Njk0LTE5ZWVkODY1LTFjYzQtNDQ1ZC04ZjA2LWY0ZWYyNjU1N2I4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzkzNmU3ODFmMjc4OGM2MGQ0YjE3MzY2Njk2YTBlMjQ5M2ZlMzAxMmE5MWFhZmE3ZDBiOTNmYjBlOTk1YTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JdyZiAgNC3_SCW2Y8cLC6bKcfv763wVKdnAGWOB5fDQ)
> 
> Hi,I have the same problem now. How did you solve it？

The model and smplx are aligned in our data. The model has no absolute scale, and the model coordinate system and size are different before and after 525. I think normalization should solve your problem.
