### ISSUE TITLE
No response for applying Thuman2.1

### ISSUE THREAD

**Issue by blacksino** [ytrock/THuman2.0-Dataset#29]
hello,I sign the agreement and still got no response

**Comment by ytrock** [comment]
Sorry for the inconvenience, What is your email address?

**Comment by blacksino** [comment]
wangla@shanghaitech.edu.cn

**Comment by ytrock** [comment]
I've checked your application and shared the dataset with you through Google Drive. Please check your email (pay attention to the trash can).
Thanks for your attention.

**Comment by blacksino** [comment]
many thanks！
