### ISSUE TITLE
mesh周围有些小离群块，请问有方法清理干净吗？

### ISSUE THREAD

**Issue by hungsing92** [ytrock/THuman2.0-Dataset#3]
如题，经观察mesh有如下小瑕疵：
<img width="267" alt="1630722746(1)" src="https://user-images.githubusercontent.com/27841572/132079603-dfa76e26-b6db-42af-a2a2-69ee0b212222.png">

因为对这块不是很熟悉，请教一下有没有什么方法处理干净。另外请教怎么把mesh转化成watertight。

非常感谢！

**Comment by ytrock** [comment]
Hi,

You can use meshlab to convert all the meshes to watertight meshes. 
For those noises around the surface, maybe you can also try to use the meshlab to remove them manually.

**Comment by hungsing92** [comment]
Many thanks！
