### ISSUE TITLE
About SMPL parameters of THUman 2.1

### ISSUE THREAD

**Issue by Jackiemin233** [ytrock/THuman2.0-Dataset#32]
Nice work on extending the dataset to over 2k scans! 
Are the SMPL parameters (i.e., the .pkl files) for Thuman 2.1 available?

**Comment by ytrock** [comment]
yes you can download it at: https://drive.google.com/file/d/194s_b2y3wpp699XVc4KNaqD6Bb7T14JS/view

**Comment by Jackiemin233** [comment]
> yes you can download it at: https://drive.google.com/file/d/194s_b2y3wpp699XVc4KNaqD6Bb7T14JS/view

Thanks for your quick reply. 
But the SMPL-X paramters is different from the SMPL parameters. My baseline method only supports the SMPL model (not SMPL-X). Can you release the SMPL parameter of Thuman2.1? 
Appreciate your time again!

**Comment by ytrock** [comment]
Ah sorry we didn't fit SMPL parameters, maybe you can check out some related GitHub repos for transferring SMPL-X
 paras to SMPL paras.

**Comment by Jackiemin233** [comment]
> Ah sorry we didn't fit SMPL parameters, maybe you can check out some related GitHub repos for transferring SMPL-X paras to SMPL paras.

Thank you all the same. I will try it.
