### ISSUE TITLE
How to generate fitted SMPL?

### ISSUE THREAD

**Issue by direcf** [ytrock/THuman2.0-Dataset#4]
Thank you for opening your great work!
It's really helpful for me.

I want to use DeepHuman2.0 and DeepHuman1.0 dataset for my 3d research.
DeepHuman1.0 basically includes smpl.obj, smpl_parameter.txt, and camera_parameter.txt.

I wonder how I can generate fitted SMPL of DeepHuman2.0 like DeepHuman1.0.
Could you elaborate on this?

**Comment by ytrock** [comment]
Hi, Thanks for your attention. 
We've just released SMPL-X fitting results, you can check out the repo and download it directly.
