### ISSUE TITLE
Reading the texture files.

### ISSUE THREAD

**Issue by LazerLikeFocus** [ytrock/THuman2.0-Dataset#7]
Its  great that we have textures with the 3d model, 
but its really had for people like me who are from non graphical background 
to figure out how to separate the texture  jpg into diff body parts.

Can you suggest solutions to read the texture jpg in atlas or normal form?
Basically I want img1(which is similar to the image you provided) to look like img2
This is an example from UVTextureConverter (which is not working on deephuman2.0 texture files)

img1
![normalindex](https://user-images.githubusercontent.com/73691611/153982230-26aad3a1-4e06-48e7-b680-45cce1d9b894.png)

img2 
![atlasindex](https://user-images.githubusercontent.com/73691611/153982373-a600f35b-ea69-41e0-ae30-63ad622b5960.png)

Any suggestions ?

**Comment by ytrock** [comment]
maybe you can leverage the corresponding SMPL-X mesh to help you segment each part.
